- platform: template
  sensors:
  ### DOORS ###
    front_door:
      entity_id: sensor.front_door_sensor_access_control
      friendly_name: 'Front Door'
      value_template: >-
        {{ is_state('sensor.front_door_sensor_access_control', '22') }}
      device_class: door

    kitchen_door:
      entity_id: sensor.kitchen_door_sensor_access_control
      friendly_name: 'Kitchen Door'
      value_template: >-
        {{ is_state('sensor.kitchen_door_sensor_access_control', '22') }}
      device_class: door

    carport_door:
      entity_id: sensor.carport_door_sensor_access_control
      friendly_name: 'Carport Door'
      value_template: >-
        {{ is_state('sensor.carport_door_sensor_access_control', '22') }}
      device_class: door

    backyard_door:
      entity_id: sensor.backyard_door_sensor2_access_control
      friendly_name: 'Backyard Door'
      value_template: >-
        {{ is_state('sensor.backyard_door_sensor2_access_control', '22') }}
      device_class: door

  ### WINDOWS ###
    front_window_left:
      entity_id: sensor.front_window_left_sensor_access_control
      friendly_name: 'Front Window (Left Half)'
      value_template: >-
        {{ is_state('sensor.front_window_left_sensor_access_control', '22') }}
      device_class: window

    front_window_right:
      entity_id: sensor.front_window_right_sensor_access_control
      friendly_name: 'Front Window (Right Half)'
      value_template: >-
        {{ is_state('sensor.front_window_right_sensor_access_control', '22') }}
      device_class: window

    dining_room_window:
      entity_id: sensor.dining_room_window_sensor_access_control
      friendly_name: 'Dining Room Window'
      value_template: >-
        {{ is_state('sensor.dining_room_window_sensor_access_control', '22') }}
      device_class: window

    connors_office_south_window:
      entity_id: sensor.connors_office_south_window_sensor_access_control
      friendly_name: "Connor's Office South Window"
      value_template: >-
        {{ is_state('sensor.connors_office_south_window_sensor_access_control', '22') }}
      device_class: window

    connors_office_west_window:
      entity_id: sensor.connors_office_west_window_sensor_access_control
      friendly_name: "Connor's Office West Window"
      value_template: >-
        {{ is_state('sensor.connors_office_west_window_sensor_access_control', '22') }}
      device_class: window

    dianas_office_window:
      entity_id: sensor.dianas_office_window_sensor_access_control
      friendly_name: "Diana's Office Window"
      value_template: >-
        {{ is_state('sensor.dianas_office_window_sensor_access_control', '22') }}
      device_class: window

    bedroom_window:
      entity_id: sensor.bedroom_window_sensor_access_control
      friendly_name: 'Bedroom Window'
      value_template: >-
        {{ is_state('sensor.bedroom_window_sensor_access_control', '22') }}
      device_class: window

    back_left_window:
      entity_id: sensor.back_left_window_sensor_access_control
      friendly_name: 'Back Left Window'
      value_template: >-
        {{ is_state('sensor.back_left_window_sensor_access_control', '22') }}
      device_class: window

    back_right_window:
      entity_id: sensor.back_right_window_sensor_access_control
      friendly_name: 'Back Right Window'
      value_template: >-
        {{ is_state('sensor.back_right_window_sensor_access_control', '22') }}
      device_class: window

    bathroom_window:
      entity_id: sensor.bathroom_window_sensor_access_control
      friendly_name: 'Bathroom Window'
      value_template: >-
        {{ is_state('sensor.bathroom_window_sensor_access_control', '22') }}
      device_class: window

  ### SMART PLUGS ###
    smart_plug_1_active:
      entity_id: sensor.smart_plug_1_current
      friendly_name: 'Smart Plug 1 Active'
      value_template: >-
        {{ states('sensor.smart_plug_1_current')|float > 0 }}
      device_class: plug

  ### MISC. ###
    bathroom_occupancy:
      friendly_name: Bathroom Occupancy
      entity_id: binary_sensor.bathroom_motion
      device_class: occupancy
      delay_off:
        seconds: 570
      value_template: >-
        {{ is_state('binary_sensor.bathroom_motion', 'on') }}

    shower:
      entity_id: sensor.bathroom_relative_humidity
      friendly_name: 'Shower'
      value_template: >-
        {{ states('sensor.bathroom_relative_humidity')|float >= 80 }}
      icon_template: 'mdi:shower-head'

    bed_occupancy_connor:
      entity_id: sensor.bed_sensor_connor_fsr
      friendly_name: Bed Occupancy (Connor)
      device_class: occupancy
      delay_off:
        seconds: 30
      value_template: >-
        {{ states('sensor.bed_sensor_connor_fsr')|float >= 0.15 }}
      icon_template: >-
        {%- set fsr = states('sensor.bed_sensor_connor_fsr')|float -%}
        {%- if (fsr < 0.15) -%}
          mdi:bed-empty
        {%- elif (fsr >= 0.15) -%}
          mdi:hotel
        {%- endif -%}

  ### CLIMATE ZONE DATA ###
    main_house_windows:
      friendly_name: Main House Windows
      device_class: window
      entity_id:
        - binary_sensor.front_window_left
        - binary_sensor.front_window_right
        - binary_sensor.dining_room_window
        - binary_sensor.connors_office_south_window
        - binary_sensor.connors_office_west_window
        - binary_sensor.dianas_office_window
        - binary_sensor.bedroom_window
      value_template: >-
        {{   is_state('binary_sensor.front_window_left', 'on')
          or is_state('binary_sensor.front_window_right', 'on')
          or is_state('binary_sensor.dining_room_window', 'on')
          or is_state('binary_sensor.connors_office_south_window', 'on')
          or is_state('binary_sensor.connors_office_west_window', 'on')
          or is_state('binary_sensor.dianas_office_window', 'on')
          or is_state('binary_sensor.bedroom_window', 'on')
        }}

    main_hourse_doors:
      friendly_name: Main House Doors
      device_class: door
      entity_id:
        - binary_sensor.front_door
      delay_on:
        minutes: 5
      delay_off:
        seconds: 30
      value_template: >-
        {{ is_state('binary_sensor.front_door', 'on') }}

    main_house_zone:
      friendly_name: Main House Zone
      device_class: opening
      entity_id:
        - binary_sensor.main_house_windows
        - binary_sensor.main_house_doors
      value_template: >-
        {{   is_state('binary_sensor.main_house_windows', 'on')
          or is_state('binary_sensor.front_window_right', 'on')
        }}

    back_room_exterior_windows:
      friendly_name: Back Room Exterior Windows
      device_class: window
      entity_id:
        - binary_sensor.back_left_window
        - binary_sensor.back_right_window
      value_template: >-
        {{   is_state('binary_sensor.back_left_window', 'on')
          or is_state('binary_sensor.back_right_window', 'on')
        }}

    back_room_exterior_doors:
      friendly_name: Back Room Exterior Doors
      device_class: door
      entity_id:
        - binary_sensor.backyard_door
        - binary_sensor.carport_door
      delay_on:
        minutes: 5
      delay_off:
        seconds: 30
      value_template: >-
        {{   is_state('binary_sensor.backyard_door', 'on')
          or is_state('binary_sensor.carport_door', 'on')
        }}

    back_room_exterior_zone:
      friendly_name: Back Room Exterior Zone
      device_class: opening
      entity_id:
        - binary_sensor.back_room_exterior_windows
        - binary_sensor.back_room_exterior_doors
      value_template: >-
        {{   is_state('binary_sensor.back_room_exterior_windows', 'on')
          or is_state('binary_sensor.back_room_exterior_doors', 'on')
        }}

  ### PRESENCE ###
    connor_presence:
      friendly_name: Connor
      device_class: presence
      entity_id: device_tracker.connor_galaxys8
      value_template: >-
        {{ is_state('device_tracker.connor_galaxys8', 'home') }}

    diana_presence:
      friendly_name: Diana
      device_class: presence
      entity_id: device_tracker.diana_pixel2
      value_template: >-
        {{ is_state('device_tracker.diana_pixel2', 'home') }}

### AV ###
- name: CEC Roku
  platform: mqtt
  device_class: power
  availability_topic: "media/bridge/status"
  #icon: mdi:play-circle
  state_topic: "media/cec/4"
  payload_on: "on"
  payload_off: "off"
