homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: !secret base_url
  #ssl_certificate: /ssl/fullchain.pem
  #ssl_key: /ssl/privkey.pem
  ip_ban_enabled: True
  login_attempts_threshold: 5

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
    include:
        entities:
            - binary_sensor.bedroom_occupancy
            - binary_sensor.connors_office_occupancy
            - binary_sensor.dianas_office_occupancy
            - binary_sensor.living_room_occupancy
        domains:
            - sensor
            - climate
            - device_tracker
            - light
            - lock
            - media_player
            - sun
            - weather
    exclude:
        entities:
            - sensor.home_temperature

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
input_datetime: !include input_datetime.yaml
input_boolean: !include input_boolean.yaml
input_text: !include input_text.yaml
input_select: !include input_select.yaml

ecobee:
  api_key: !secret ecobee_api_key

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key
  device_config:
    light.connors_office_light:
        polling_intensity: 1
    light.bedroom_light:
        polling_intensity: 1

device_tracker:
  - platform: nmap_tracker
    hosts: 10.31.36.0/24
    new_device_defaults:
      track_new_devices: False
    consider_home: 300
    interval_seconds: 60

influxdb:
  host: !secret influx_ip
  username: !secret influx_user
  password: !secret influx_password