# VIEWS #
default_view:
    name: Home
    view: yes
    icon: mdi:home
    entities:
        - group.general
        - group.bedroom
        - group.living_room
        - group.connors_office
        - group.dianas_office
        - group.automation

people_view:
    name: People
    icon: mdi:account-multiple
    view: yes
    entities:
        - group.people
        - group.diabetes

media_view:
    name: Media
    view: yes
    icon: mdi:audio-video
    entities:
        - media_player.roku_5y25a2192945

alarmclock_view:
    name: Alarms
    icon: mdi:alarm
    view: yes
    entities:
        - group.alarm1
        - group.alarm2
        - group.alarm3
        - group.alarm4
        - group.alarm5

config_view:
    name: Config
    icon: mdi:remote
    view: yes
    entities:
        - group.zwave
        - group.batteries

# GROUPS #
general:
    name: General
    view: no
    entities:
        - lock.front_door
        - climate.home
        - sensor.home_humidity
        - light.hallway_light
        - input_select.hallway_light_mode

people:
    name: Presence
    view: no
    entities:
      - device_tracker.connor_galaxys8
      - device_tracker.diana_pixel2

inside_lights:
    name: Inside Lights
    entities:
        - light.connors_office_light
        - light.dianas_office_light
        - light.bedroom_light
        - light.hallway_light
        - light.dining_room_light
        - light.bathroom_light

inside_lights_except_bedroom:
    name: Inside Lights Except Bedroom
    entities:
        - light.connors_office_light
        - light.dianas_office_light
        - light.hallway_light
        - light.dining_room_light
        - light.bathroom_light

#diabetes:
#    name: Diabetes
#    view: no
#    entities:
#      - sensor.blood_glucose_level

connors_office:
    name: "Connor's Office"
    view: no
    entities:
      - light.connors_office_light
      - binary_sensor.connor_office_occupancy
      - sensor.connor_office_temperature

dianas_office:
    name: "Diana's Office"
    view: no
    entities:
      - light.dianas_office_light
      - binary_sensor.diana_office_occupancy
      - sensor.diana_office_temperature

bedroom:
    name: Bedroom
    view: no
    entities:
      - light.bedroom_light
      - binary_sensor.bedroom_occupancy
      - sensor.bedroom_temperature

living_room:
    name: Living Room
    view: no
    entities:
        - binary_sensor.living_room_occupancy
        - sensor.living_room_temperature

batteries:
    name: Batteries
    view: no
    entities:
        - sensor.schlage_frontdoor_battery

zwave:
    name: Z-Wave
    entities:
        - zwave.aeotec_zw090_zstick_gen5_us
        - zwave.connors_office_light
        - zwave.dianas_office_light
        - zwave.bedroom_light
        - zwave.hallway_light
        - zwave.front_door_lock

automation:
    name: Automation
    entities:
        - input_boolean.ecobee_auto_home_away
        - input_select.connors_office_light_mode
        - input_select.dianas_office_light_mode
        - input_select.bedroom_light_mode

alarm1:
    control: hidden
    icon: mdi:alarm
    entities:
        - input_text.alarm1_name
        - input_boolean.alarm1_enabled
        - input_datetime.alarm1_datetime
        - input_boolean.alarm1_sunday
        - input_boolean.alarm1_monday
        - input_boolean.alarm1_tuesday
        - input_boolean.alarm1_wednesday
        - input_boolean.alarm1_thursday
        - input_boolean.alarm1_friday
        - input_boolean.alarm1_saturday

alarm2:
    control: hidden
    icon: mdi:alarm
    entities:
        - input_text.alarm2_name
        - input_boolean.alarm2_enabled
        - input_datetime.alarm2_datetime
        - input_boolean.alarm2_sunday
        - input_boolean.alarm2_monday
        - input_boolean.alarm2_tuesday
        - input_boolean.alarm2_wednesday
        - input_boolean.alarm2_thursday
        - input_boolean.alarm2_friday
        - input_boolean.alarm2_saturday

alarm3:
    control: hidden
    icon: mdi:alarm
    entities:
        - input_text.alarm3_name
        - input_boolean.alarm3_enabled
        - input_datetime.alarm3_datetime
        - input_boolean.alarm3_sunday
        - input_boolean.alarm3_monday
        - input_boolean.alarm3_tuesday
        - input_boolean.alarm3_wednesday
        - input_boolean.alarm3_thursday
        - input_boolean.alarm3_friday
        - input_boolean.alarm3_saturday

alarm4:
    control: hidden
    icon: mdi:alarm
    entities:
        - input_text.alarm4_name
        - input_boolean.alarm4_enabled
        - input_datetime.alarm4_datetime
        - input_boolean.alarm4_sunday
        - input_boolean.alarm4_monday
        - input_boolean.alarm4_tuesday
        - input_boolean.alarm4_wednesday
        - input_boolean.alarm4_thursday
        - input_boolean.alarm4_friday
        - input_boolean.alarm4_saturday

alarm5:
    control: hidden
    icon: mdi:alarm
    entities:
        - input_text.alarm5_name
        - input_boolean.alarm5_enabled
        - input_datetime.alarm5_datetime
        - input_boolean.alarm5_sunday
        - input_boolean.alarm5_monday
        - input_boolean.alarm5_tuesday
        - input_boolean.alarm5_wednesday
        - input_boolean.alarm5_thursday
        - input_boolean.alarm5_friday
        - input_boolean.alarm5_saturday