- platform: yr
- platform: template
  sensors:
#    blood_glucose_level:
#      friendly_name: 'Blood Glucose Level'
#      value_template: >
#        {{ state_attr('sensor.blood_glucose', 'sgv') }}
#      unit_of_measurement: 'mg/dL'
#      icon_template: >
#        {%- set direction = state_attr('sensor.blood_glucose', 'direction') -%}
#        {%- if (direction == 'Flat') -%}
#          mdi:arrow-right
#        {%- elif (direction == 'FortyFiveUp') -%}
#          mdi:arrow-top-right
#        {%- elif (direction == 'FortyFiveDown') -%}
#          mdi:arrow-bottom-right
#        {%- elif (direction == 'SingleUp') -%}
#          mdi:arrow-up
#        {%- elif (direction == 'DoubleUp') -%}
#          mdi:arrow-up-thick
#        {%- elif (direction == 'SingleDown') -%}
#          mdi:arrow-down
#        {%- elif (direction == 'DoubleDown') -%}
#          mdi:arrow-down-thick
#        {%- endif -%}

  ### BATTERIES ###
    front_window_left_sensor_battery:
      entity_id: zwave.front_window_left_sensor
      friendly_name: 'Front Window (Left Half) Sensor Battery'
      value_template: '{{ states.zwave.front_window_left_sensor.attributes.battery_level }}'
      device_class: battery

    front_window_right_sensor_battery:
      entity_id: zwave.front_window_right_sensor
      friendly_name: 'Front Window (Right Half) Sensor Battery'
      value_template: '{{ states.zwave.front_window_right_sensor.attributes.battery_level }}'
      device_class: battery

    dining_room_window_sensor_battery:
      entity_id: zwave.dining_room_window_sensor
      friendly_name: 'Dining Room Window Sensor Battery'
      value_template: '{{ states.zwave.dining_room_window_sensor.attributes.battery_level }}'
      device_class: battery

    connors_office_west_window_sensor_battery:
      entity_id: zwave.connors_office_west_window_sensor
      friendly_name: "Connor's Office West Window Sensor Battery"
      value_template: '{{ states.zwave.connors_office_west_window_sensor.attributes.battery_level }}'
      device_class: battery

    connors_office_south_window_sensor_battery:
      entity_id: zwave.connors_office_south_window_sensor
      friendly_name: "Connor's Office South Window Sensor Battery"
      value_template: '{{ states.zwave.connors_office_south_window_sensor.attributes.battery_level }}'
      device_class: battery

    dianas_office_window_sensor_battery:
      entity_id: zwave.dianas_office_window_sensor
      friendly_name: "Dianas Office Window Sensor Battery"
      value_template: '{{ states.zwave.dianas_office_window_sensor.attributes.battery_level }}'
      device_class: battery

    bathroom_window_sensor_battery:
      entity_id: zwave.bathroom_window_sensor
      friendly_name: 'Bathroom Window Sensor Battery'
      value_template: '{{ states.zwave.bathroom_window_sensor.attributes.battery_level }}'
      device_class: battery

    bedroom_window_sensor_battery:
      entity_id: zwave.bedroom_window_sensor
      friendly_name: 'Bedroom Window Sensor Battery'
      value_template: '{{ states.zwave.bedroom_window_sensor.attributes.battery_level }}'
      device_class: battery

    back_left_window_sensor_battery:
      entity_id: zwave.back_left_window_sensor
      friendly_name: 'Back Left Window Sensor Battery'
      value_template: '{{ states.zwave.back_left_window_sensor.attributes.battery_level }}'
      device_class: battery

    back_right_window_sensor_battery:
      entity_id: zwave.back_right_window_sensor
      friendly_name: 'Back Right Window Sensor Battery'
      value_template: '{{ states.zwave.back_right_window_sensor.attributes.battery_level }}'
      device_class: battery

    front_door_sensor_2_battery:
      entity_id: zwave.front_door_sensor_2
      friendly_name: 'Front Door Sensor Battery'
      value_template: '{{ states.zwave.front_door_sensor_2.attributes.battery_level }}'
      device_class: battery

    kitchen_door_sensor_battery:
      entity_id: zwave.kitchen_door_sensor
      friendly_name: 'Kitchen Door Sensor Battery'
      value_template: '{{ states.zwave.kitchen_door_sensor.attributes.battery_level }}'
      device_class: battery

    backyard_door_sensor_battery:
      entity_id: zwave.backyard_door_sensor
      friendly_name: 'Backyard Door Sensor Battery'
      value_template: '{{ states.zwave.backyard_door_sensor.attributes.battery_level }}'
      device_class: battery

    carport_door_sensor_battery:
      entity_id: zwave.carport_door_sensor
      friendly_name: 'Carport Door Sensor Battery'
      value_template: '{{ states.zwave.carport_door_sensor.attributes.battery_level }}'
      device_class: battery

    front_door_lock_battery:
      entity_id: zwave.front_door_lock
      friendly_name: 'Front Door Lock Battery'
      value_template: '{{ states.zwave.front_door_lock.attributes.battery_level }}'
      device_class: battery

    bathroom_multisensor_6_battery:
      entity_id: zwave.bathroom_multisensor_6
      friendly_name: 'Bathroom MultiSensor 6 Battery'
      value_template: '{{ states.zwave.bathroom_multisensor_6.attributes.battery_level }}'
      device_class: battery

### AV ###
- name: CEC Receiver Volume
  platform: mqtt
  state_topic: "media/cec/volume"
  availability_topic: "media/bridge/status"
  unit_of_measurement: '%'

- platform: sonarr
  api_key: !secret sonarr_api_key
  host: media.ipa.connorcg.com


### MISC ###
- platform: srp_energy
  username: !secret srp_username
  password: !secret srp_password
  id: !secret srp_id