resources:
  - url: /local/slider-entity-row.js?v=2
    type: js
    git: https://github.com/thomasloven/lovelace-slider-entity-row
  - url: /local/monster-card.js?v=1
    type: js
    git: https://raw.githubusercontent.com/ciotlosm/custom-lovelace/master/monster-card/monster-card.js
  - url: /local/vertical-stack-in-card.js?v=1
    type: js
    git: https://github.com/custom-cards/vertical-stack-in-card

title: Home
views:
  - title: Home
    icon: mdi:home
    id: home
    #theme:
    cards:
      - title: General
        id: general
        type: entities
        entities:
          - label: Climate
            type: section
          - entity: climate.home
            name: Ecobee
          - binary_sensor.main_house_zone
          - binary_sensor.back_room_exterior_zone
          - label: Presence
            type: section
          - binary_sensor.connor_presence
          - binary_sensor.diana_presence
          - label: Security
            type: section
          - lock.front_door_lock
          - sensor.home_security_armed
          - sensor.home_security_fired

      - title: Routines
        id: routines
        type: entities
        entities:
          - name: Turn off all lights
            type: call-service
            icon: mdi:lightbulb
            action_name: Run
            service: light.turn_off

      - title: Bedroom
        type: custom:vertical-stack-in-card
        id: bedroom_stack
        cards:
          - id: bedroom_light
            type: light
            entity: light.bedroom_light
          - id: bedroom_glance
            type: glance
            entities:
              - entity: sensor.bedroom_temperature
                name: Temp
              #- entity: binary_sensor.bedroom_occupancy
              #  name: Presence
              - entity: input_select.bedroom_light_mode
                name: Light Mode
                hold_action: call-service
                service: input_select.select_option
                service_data:
                  entity_id: input_select.bedroom_light_mode
                  option: Automatic
              - entity: binary_sensor.bedroom_window
                name: Window
              #- binary_sensor.bed_occupancy_connor

      - title: Connor's Office
        type: custom:vertical-stack-in-card
        id: connors_office_stack
        cards:
          - id: connors_office_light
            type: light
            entity: light.connors_office_light
          - id: connors_office_glance
            type: glance
            entities:
              - entity: sensor.connor_office_temperature
                name: Temp
              #- entity: binary_sensor.connor_office_occupancy
              #  name: Presence
              - entity: input_select.connors_office_light_mode
                name: Light Mode
                hold_action: call-service
                service: input_select.select_option
                service_data:
                  entity_id: input_select.connors_office_light_mode
                  option: Automatic
              - entity: binary_sensor.connors_office_south_window
                name: South
              - entity: binary_sensor.connors_office_west_window
                name: West

      - title: Diana's Office
        type: custom:vertical-stack-in-card
        id: dianas_office_stack
        cards:
          - id: dianas_office_light
            type: light
            entity: light.dianas_office_light
          - id: dianas_office_glance
            type: glance
            entities:
              - entity: sensor.diana_office_temperature
                name: Temp
              #- entity: binary_sensor.diana_office_occupancy
              #  name: Presence
              - entity: input_select.dianas_office_light_mode
                name: Light Mode
                hold_action: call-service
                service: input_select.select_option
                service_data:
                  entity_id: input_select.dianas_office_light_mode
                  option: Automatic
              - entity: binary_sensor.dianas_office_window
                name: Window

      - title: Living Room
        type: custom:vertical-stack-in-card
        id: living_room_stack
        cards:
        - id: living_room_glance
          type: glance
          columns: 3
          entities:
            - entity: sensor.living_room_temperature
              name: Temp
            #- entity: binary_sensor.living_room_occupancy
            #  name: Presence
            - entity: binary_sensor.smart_plug_1_active
              name: Projector
              icon: mdi:projector
              hold_action: call-service
              service: switch.turn_on
              service_data:
                entity_id: switch.smart_plug_1_switch
            - name: Roku
              entity: media_player.living_room_roku
            - binary_sensor.front_door
            - entity: binary_sensor.front_window_left
              name: Left Half
            - entity: binary_sensor.front_window_right
              name: Right Half

      - title: Dining Room
        type: custom:vertical-stack-in-card
        id: dining_room_stack
        cards:
          - id: dining_room_light
            type: light
            entity: light.dining_room_light
          - id: dining_room_glance
            type: glance
            entities:
            - entity: input_select.dining_room_light_mode
              name: Light Mode
              hold_action: call-service
              service: input_select.select_option
              service_data:
                entity_id: input_select.dining_room_light_mode
                option: Automatic
            - entity: binary_sensor.dining_room_window
              name: Window

      - title: Hallway
        type: custom:vertical-stack-in-card
        id: hallway_stack
        cards:
          - id: hallway_light
            type: light
            entity: light.hallway_light
          - id: hallway_glance
            type: glance
            entities:
            - entity: sensor.home_temperature
              name: Temp
            - entity: input_select.hallway_light_mode
              name: Light Mode
              hold_action: call-service
              service: input_select.select_option
              service_data:
                entity_id: input_select.hallway_light_mode
                option: Automatic

      - title: Bathroom
        type: custom:vertical-stack-in-card
        id: bathroom_stack
        cards:
          - id: bathroom_light
            type: light
            entity: light.bathroom_light
          - id: bathroom_glance
            type: glance
            columns: 4
            entities:
            - entity: sensor.bathroom_temperature
              name: Temp
            - entity: binary_sensor.bathroom_motion
              name: Motion
            - entity: input_select.bathroom_light_mode
              name: Light Mode
            - binary_sensor.shower
            - entity: binary_sensor.bathroom_window
              name: Window
            - entity: sensor.bathroom_luminance
              name: Lux
            - entity: sensor.bathroom_relative_humidity
              name: Humidity

      - title: Back Room
        id: back_room
        type: glance
        columns: 3
        show_state: false
        entities:
          - entity: binary_sensor.backyard_door
            name: Backyard Door
          - entity: binary_sensor.carport_door
            name: Carport Door
          - entity: binary_sensor.kitchen_door
            name: Kitchen Door
          - entity: binary_sensor.back_left_window
            name: Left Window
          - entity: binary_sensor.back_right_window
            name: Right Window

      #- title: Lights
      #  id: light_groups
      #  type: entities
      #  entities:
      #    - entity: group.all_lights
      #      name: All Lights
      #    - group.inside_lights
      #    - group.inside_lights_except_bedroom

  - title: Alarms
    id: alarms
    icon: mdi:alarm
    cards:
      - title: Alarm1
        id: alarm1
        type: entities
        show_header_toggle: false
        entities:
        #- input_text.alarm1_name
        - input_boolean.alarm1_enabled
        - input_datetime.alarm1_datetime
        - input_boolean.alarm1_sunday
        - input_boolean.alarm1_monday
        - input_boolean.alarm1_tuesday
        - input_boolean.alarm1_wednesday
        - input_boolean.alarm1_thursday
        - input_boolean.alarm1_friday
        - input_boolean.alarm1_saturday

      - title: Alarm2
        id: alarm2
        type: entities
        show_header_toggle: false
        entities:
        #- input_text.alarm2_name
        - input_boolean.alarm2_enabled
        - input_datetime.alarm2_datetime
        - input_boolean.alarm2_sunday
        - input_boolean.alarm2_monday
        - input_boolean.alarm2_tuesday
        - input_boolean.alarm2_wednesday
        - input_boolean.alarm2_thursday
        - input_boolean.alarm2_friday
        - input_boolean.alarm2_saturday

      - title: Alarm3
        id: alarm3
        type: entities
        show_header_toggle: false
        entities:
        #- input_text.alarm3_name
        - input_boolean.alarm3_enabled
        - input_datetime.alarm3_datetime
        - input_boolean.alarm3_sunday
        - input_boolean.alarm3_monday
        - input_boolean.alarm3_tuesday
        - input_boolean.alarm3_wednesday
        - input_boolean.alarm3_thursday
        - input_boolean.alarm3_friday
        - input_boolean.alarm3_saturday

      - title: Alarm4
        id: alarm4
        type: entities
        show_header_toggle: false
        entities:
        #- input_text.alarm4_name
        - input_boolean.alarm4_enabled
        - input_datetime.alarm4_datetime
        - input_boolean.alarm4_sunday
        - input_boolean.alarm4_monday
        - input_boolean.alarm4_tuesday
        - input_boolean.alarm4_wednesday
        - input_boolean.alarm4_thursday
        - input_boolean.alarm4_friday
        - input_boolean.alarm4_saturday

      - title: Alarm5
        id: alarm5
        type: entities
        show_header_toggle: false
        entities:
        #- input_text.alarm5_name
        - input_boolean.alarm5_enabled
        - input_datetime.alarm5_datetime
        - input_boolean.alarm5_sunday
        - input_boolean.alarm5_monday
        - input_boolean.alarm5_tuesday
        - input_boolean.alarm5_wednesday
        - input_boolean.alarm5_thursday
        - input_boolean.alarm5_friday
        - input_boolean.alarm5_saturday

  - title: Climate
    id: climate
    icon: mdi:weather-sunny
    cards:
      - type: thermostat
        id: thermostat
        entity: climate.home
      - type: weather-forecast
        id: forecast
        entity: weather.home
      - type: iframe
        id: temp_history
        title: History
        url: http://10.31.36.11:3000/dashboard-solo/snapshot/AHM5vJRewYGhx2eg6iJiy6KFhRYeu1I7?orgId=1&panelId=2&from=1530396946437&to=1530440146437&theme=light

  - title: Media
    id: media
    icon: mdi:audio-video
    cards:
      - type: media-control
        id: roku
        entity: media_player.living_room_roku
      - type: entities
        id: media_entities
        entities:
          - entity: binary_sensor.smart_plug_1_active
            name: Projector State
            icon: mdi:projector
          - entity: switch.smart_plug_1_switch
            name: Projector Power


  - title: Automations
    id: automations
    icon: mdi:robot
    cards:
      - type: "custom:monster-card"
        id: all_automations
        card:
          type: entities
          title: All Automations
        filter:
          include:
            - entity_id: "input_boolean.*_automation"

  - title: Z-Wave
    id: zwave
    icon: mdi:z-wave
    cards:
      - type: "custom:monster-card"
        id: zwave_entities
        card:
          type: entities
          title: Z-Wave
        filter:
          include:
            - domain: zwave

      - type: "custom:monster-card"
        id: smart-plug-1
        card:
          type: entities
          title: Smart Plug 1
        filter:
          include:
            - entity_id: "*.smart_plug_1*"

      - type: "custom:monster-card"
        id: zwave_batteries
        card:
          type: entities
          title: Batteries
        filter:
          include:
            - entity_id: "sensor.*_battery"

      - title: Bathroom MultiSensor
        id: bathroom_multisensor
        type: entities
        entities:
          - sensor.bathroom_alarm_level
          - sensor.bathroom_alarm_type
          - sensor.bathroom_burglar
          - sensor.bathroom_sourcenodeid
          - sensor.bathroom_temperature
          - sensor.bathroom_ultraviolet

      - title: Front Door Lock
        id: front_door_lock
        type: entities
        entities:
          - sensor.front_door_lock_access_control
          - sensor.front_door_lock_alarm_level
          - sensor.front_door_lock_alarm_type
          - sensor.front_door_lock_burglar
          - sensor.front_door_lock_power_management
          - sensor.front_door_lock_sourcenodeid
          - sensor.front_door_lock_system



