resources:
  - url: /local/slider-entity-row.js?v=2
    type: js
    git: https://github.com/thomasloven/lovelace-slider-entity-row

title: Home
views:
  - title: Home
    icon: mdi:home
    #theme:
    cards:
      - title: General
        type: entities
        entities:
          - lock.front_door_lock
          - climate.home
          - sensor.home_humidity
          - type: divider
          - device_tracker.connor_galaxys8
          - device_tracker.diana_pixel2

      - title: Bedroom
        type: entities
        show_header_toggle: false
        entities:
          - entity: light.bedroom_light
            name: Light
            type: custom:slider-entity-row
          - entity: input_select.bedroom_light_mode
            name: Light Mode
          - entity: binary_sensor.bedroom_occupancy
            name: Occupancy
          - entity: sensor.bedroom_temperature
            name: Temperature

      - title: Connor's Office
        type: entities
        show_header_toggle: false
        entities:
          - entity: light.connors_office_light
            name: Light
            type: custom:slider-entity-row
          - entity: input_select.connors_office_light_mode
            name: Light Mode
          - entity: binary_sensor.connor_office_occupancy
            name: Occupancy
          - entity: sensor.connor_office_temperature
            name: Temperature

      - title: Diana's Office
        type: entities
        show_header_toggle: false
        entities:
          - entity: light.dianas_office_light
            name: Light
            type: custom:slider-entity-row
          - entity: input_select.dianas_office_light_mode
            name: Light Mode
          - entity: binary_sensor.diana_office_occupancy
            name: Occupancy
          - entity: sensor.diana_office_temperature
            name: Temperature

      - title: Living Room
        type: entities
        show_header_toggle: false
        entities:
          - entity: binary_sensor.living_room_occupancy
            name: Occupancy
          - entity: sensor.living_room_temperature
            name: Temperature

      - title: Dining Room
        type: entities
        show_header_toggle: false
        entities:
          - entity: light.dining_room_light
            name: Light
            type: custom:slider-entity-row
          - entity: input_select.dining_room_light_mode
            name: Light Mode

      - title: Hallway
        type: entities
        show_header_toggle: false
        entities:
          - entity: light.hallway_light
            name: Light
            type: custom:slider-entity-row
          - entity: input_select.hallway_light_mode
            name: Light Mode

      - title: Bathroom
        type: entities
        show_header_toggle: false
        entities:
          - entity: light.bathroom_light
            name: Light
            type: custom:slider-entity-row
          - entity: input_select.bathroom_light_mode
            name: Light Mode
          - binary_sensor.bathroom_motion
          - sensor.bathroom_luminance
          - sensor.bathroom_relative_humidity

      - title: Lights
        type: entities
        entities:
          - entity: group.all_lights
            name: All Lights
          - group.inside_lights
          - group.inside_lights_except_bedroom

      - title: Automations
        type: entities
        entities:
          - input_boolean.smart_unlock_automation
          - input_boolean.light_brightness_automation
          - input_boolean.light_double_tap_automation
          - input_boolean.light_presence_automation
          - input_boolean.alarm_clock_automation
          - input_boolean.ecobee_auto_home_away
          - input_boolean.room_presence
          - input_boolean.low_battery_alert

  - title: Alarms
    icon: mdi:alarm
    cards:
      - title: Alarm1
        type: entities
        show_header_toggle: false
        entities:
        #- input_text.alarm1_name
        - input_boolean.alarm1_enabled
        - input_datetime.alarm1_datetime
        - input_boolean.alarm1_sunday
        - input_boolean.alarm1_monday
        - input_boolean.alarm1_tuesday
        - input_boolean.alarm1_wednesday
        - input_boolean.alarm1_thursday
        - input_boolean.alarm1_friday
        - input_boolean.alarm1_saturday

      - title: Alarm2
        type: entities
        show_header_toggle: false
        entities:
        #- input_text.alarm2_name
        - input_boolean.alarm2_enabled
        - input_datetime.alarm2_datetime
        - input_boolean.alarm2_sunday
        - input_boolean.alarm2_monday
        - input_boolean.alarm2_tuesday
        - input_boolean.alarm2_wednesday
        - input_boolean.alarm2_thursday
        - input_boolean.alarm2_friday
        - input_boolean.alarm2_saturday

      - title: Alarm3
        type: entities
        show_header_toggle: false
        entities:
        #- input_text.alarm3_name
        - input_boolean.alarm3_enabled
        - input_datetime.alarm3_datetime
        - input_boolean.alarm3_sunday
        - input_boolean.alarm3_monday
        - input_boolean.alarm3_tuesday
        - input_boolean.alarm3_wednesday
        - input_boolean.alarm3_thursday
        - input_boolean.alarm3_friday
        - input_boolean.alarm3_saturday

      - title: Alarm4
        type: entities
        show_header_toggle: false
        entities:
        #- input_text.alarm4_name
        - input_boolean.alarm4_enabled
        - input_datetime.alarm4_datetime
        - input_boolean.alarm4_sunday
        - input_boolean.alarm4_monday
        - input_boolean.alarm4_tuesday
        - input_boolean.alarm4_wednesday
        - input_boolean.alarm4_thursday
        - input_boolean.alarm4_friday
        - input_boolean.alarm4_saturday

      - title: Alarm5
        type: entities
        show_header_toggle: false
        entities:
        #- input_text.alarm5_name
        - input_boolean.alarm5_enabled
        - input_datetime.alarm5_datetime
        - input_boolean.alarm5_sunday
        - input_boolean.alarm5_monday
        - input_boolean.alarm5_tuesday
        - input_boolean.alarm5_wednesday
        - input_boolean.alarm5_thursday
        - input_boolean.alarm5_friday
        - input_boolean.alarm5_saturday

  - title: Climate
    icon: mdi:weather-sunny
    cards:
      - type: weather-forecast
        entity: weather.home
      - type: iframe
        title: History
        url: !secret temp_iframe_url

  - title: Media
    icon: mdi:audio-video
    cards:
      - type: media-control
        entity: media_player.roku_5y25a2192945

  - title: z-Wave Devices
    icon: mdi:remote
    cards:
      - title: Z-Wave
        type: entities
        entities:
          - zwave.aeotec_zw090_zstick_gen5_us
          - zwave.connors_office_light
          - zwave.dianas_office_light
          - zwave.bedroom_light
          - zwave.hallway_light
          - zwave.dining_room_light
          - zwave.bathroom_light
          - zwave.front_door_lock
          - zwave.bathroom_multisensor_6

      - title: Batteries
        type: entities
        entities:
          - sensor.schlage_frontdoor_battery
          - sensor.bathroom_multisensor_6_battery

      - title: Aeotec MultiSensor 01
        type: entities
        entities:
          - sensor.bathroom_alarm_level
          - sensor.bathroom_alarm_type
          - sensor.bathroom_burglar
          - sensor.bathroom_sourcenodeid
          - sensor.bathroom_temperature
          - sensor.bathroom_ultraviolet
