resources:
  - url: /local/slider-entity-row.js?v=2
    type: js
    git: https://github.com/thomasloven/lovelace-slider-entity-row
  - url: /local/monster-card.js?v=1
    type: js
    git: https://raw.githubusercontent.com/ciotlosm/custom-lovelace/master/monster-card/monster-card.js

title: Home
views:
  - title: Home
    icon: mdi:home
    id: home
    #theme:
    cards:
      - title: General
        id: general
        type: entities
        entities:
          - sensor.home_humidity
          - climate.home
          - type: divider
          - binary_sensor.connor_presence
          - binary_sensor.diana_presence

      - title: Bedroom
        id: bedroom
        type: entities
        show_header_toggle: false
        entities:
          - entity: light.bedroom_light
            name: Light
            type: custom:slider-entity-row
          - entity: input_select.bedroom_light_mode
            name: Light Mode
          - entity: binary_sensor.bedroom_window
            name: Window
          - entity: binary_sensor.bedroom_occupancy
            name: Occupancy
          - entity: sensor.bedroom_temperature
            name: Temperature

      - title: Connor's Office
        id: connors_office
        type: entities
        show_header_toggle: false
        entities:
          - entity: light.connors_office_light
            name: Light
            type: custom:slider-entity-row
          - entity: input_select.connors_office_light_mode
            name: Light Mode
          - entity: binary_sensor.connors_office_south_window
            name: South Window
          - entity: binary_sensor.connors_office_west_window
            name: West Window
          - entity: binary_sensor.connor_office_occupancy
            name: Occupancy
          - entity: sensor.connor_office_temperature
            name: Temperature

      - title: Diana's Office
        id: dianas_office
        type: entities
        show_header_toggle: false
        entities:
          - entity: light.dianas_office_light
            name: Light
            type: custom:slider-entity-row
          - entity: input_select.dianas_office_light_mode
            name: Light Mode
          - entity: binary_sensor.dianas_office_window
            name: Window
          - entity: binary_sensor.diana_office_occupancy
            name: Occupancy
          - entity: sensor.diana_office_temperature
            name: Temperature

      - title: Living Room
        id: living_room
        type: entities
        show_header_toggle: false
        entities:
          - lock.front_door_lock
          - binary_sensor.front_door
          - entity: binary_sensor.front_window_left
            name: Window (Left Half)
          - entity: binary_sensor.front_window_right
            name: Window (Right Half)
          - entity: binary_sensor.living_room_occupancy
            name: Occupancy
          - entity: sensor.living_room_temperature
            name: Temperature
          - entity: binary_sensor.smart_plug_2_active
            name: Projector
            icon: mdi:projector

      - title: Dining Room
        id: dining_room
        type: entities
        show_header_toggle: false
        entities:
          - entity: light.dining_room_light
            name: Light
            type: custom:slider-entity-row
          - entity: input_select.dining_room_light_mode
            name: Light Mode
          - entity: binary_sensor.dining_room_window
            name: Window

      - title: Hallway
        id: hallway
        type: entities
        show_header_toggle: false
        entities:
          - entity: light.hallway_light
            name: Light
            type: custom:slider-entity-row
          - entity: input_select.hallway_light_mode
            name: Light Mode

      - title: Bathroom
        id: bathroom
        type: entities
        show_header_toggle: false
        entities:
          - entity: light.bathroom_light
            name: Light
            type: custom:slider-entity-row
          - entity: input_select.bathroom_light_mode
            name: Light Mode
          - entity: binary_sensor.bathroom_window
            name: Window
          - binary_sensor.bathroom_motion
          - sensor.bathroom_luminance
          - sensor.bathroom_relative_humidity
          - binary_sensor.shower

      - title: Back Room
        id: back_room
        type: entities
        show_header_toggle: false
        entities:
          - binary_sensor.backyard_door
          - binary_sensor.carport_door
          - binary_sensor.kitchen_door
          - entity: binary_sensor.back_left_window
            name: Left Window
          - entity: binary_sensor.back_right_window
            name: Right Window

      - title: Lights
        id: light_groups
        type: entities
        entities:
          - entity: group.all_lights
            name: All Lights
          - group.inside_lights
          - group.inside_lights_except_bedroom

  - title: Alarms
    id: alarms
    icon: mdi:alarm
    cards:
      - title: Alarm1
        id: alarm1
        type: entities
        show_header_toggle: false
        entities:
        #- input_text.alarm1_name
        - input_boolean.alarm1_enabled
        - input_datetime.alarm1_datetime
        - input_boolean.alarm1_sunday
        - input_boolean.alarm1_monday
        - input_boolean.alarm1_tuesday
        - input_boolean.alarm1_wednesday
        - input_boolean.alarm1_thursday
        - input_boolean.alarm1_friday
        - input_boolean.alarm1_saturday

      - title: Alarm2
        id: alarm2
        type: entities
        show_header_toggle: false
        entities:
        #- input_text.alarm2_name
        - input_boolean.alarm2_enabled
        - input_datetime.alarm2_datetime
        - input_boolean.alarm2_sunday
        - input_boolean.alarm2_monday
        - input_boolean.alarm2_tuesday
        - input_boolean.alarm2_wednesday
        - input_boolean.alarm2_thursday
        - input_boolean.alarm2_friday
        - input_boolean.alarm2_saturday

      - title: Alarm3
        id: alarm3
        type: entities
        show_header_toggle: false
        entities:
        #- input_text.alarm3_name
        - input_boolean.alarm3_enabled
        - input_datetime.alarm3_datetime
        - input_boolean.alarm3_sunday
        - input_boolean.alarm3_monday
        - input_boolean.alarm3_tuesday
        - input_boolean.alarm3_wednesday
        - input_boolean.alarm3_thursday
        - input_boolean.alarm3_friday
        - input_boolean.alarm3_saturday

      - title: Alarm4
        id: alarm4
        type: entities
        show_header_toggle: false
        entities:
        #- input_text.alarm4_name
        - input_boolean.alarm4_enabled
        - input_datetime.alarm4_datetime
        - input_boolean.alarm4_sunday
        - input_boolean.alarm4_monday
        - input_boolean.alarm4_tuesday
        - input_boolean.alarm4_wednesday
        - input_boolean.alarm4_thursday
        - input_boolean.alarm4_friday
        - input_boolean.alarm4_saturday

      - title: Alarm5
        id: alarm5
        type: entities
        show_header_toggle: false
        entities:
        #- input_text.alarm5_name
        - input_boolean.alarm5_enabled
        - input_datetime.alarm5_datetime
        - input_boolean.alarm5_sunday
        - input_boolean.alarm5_monday
        - input_boolean.alarm5_tuesday
        - input_boolean.alarm5_wednesday
        - input_boolean.alarm5_thursday
        - input_boolean.alarm5_friday
        - input_boolean.alarm5_saturday

  - title: Climate
    id: climate
    icon: mdi:weather-sunny
    cards:
      - type: thermostat
        id: thermostat
        entity: climate.home
      - type: weather-forecast
        id: forecast
        entity: weather.home
      - type: iframe
        id: temp_history
        title: History
        url: http://10.31.36.11:3000/dashboard-solo/snapshot/AHM5vJRewYGhx2eg6iJiy6KFhRYeu1I7?orgId=1&panelId=2&from=1530396946437&to=1530440146437&theme=light

  - title: Media
    id: media
    icon: mdi:audio-video
    cards:
      - type: media-control
        id: roku
        entity: media_player.living_room_roku
      - type: entities
        id: media_entities
        entities:
          - entity: binary_sensor.smart_plug_2_active
            name: Projector State
            icon: mdi:projector
          - entity: switch.smart_plug_2_switch
            name: Projector Power


  - title: Automations
    id: automations
    cards:
      - type: "custom:monster-card"
        id: all_automations
        card:
          type: entities
          title: All Automations
        filter:
          include:
            - entity_id: "input_boolean.*_automation"

  - title: Doors & Windows
    id: doors_windows
    cards:
      - title: 'Home Security'
        id: home_security
        type: entities
        entities:
          - sensor.home_security_armed
          - sensor.home_security_fired

      - title: Climate Zones
        id: climate_zones
        type: entities
        entities:
          - sensor.main_house_zone
          - sensor.back_room_exterior_zone

      - type: "custom:monster-card"
        id: all_windows
        card:
          type: entities
          title: All Windows
        filter:
          include:
            - entity_id: "binary_sensor.*window(?:_left|_right)?"

      - type: "custom:monster-card"
        id: all_doors
        card:
          type: entities
          title: All Doors
        filter:
          include:
            - entity_id: "binary_sensor.*door"

  - title: Z-Wave
    id: zwave
    cards:
      - type: "custom:monster-card"
        id: zwave_entities
        card:
          type: entities
          title: Z-Wave
        filter:
          include:
            - domain: zwave

      - type: "custom:monster-card"
        id: smart-plug-1
        card:
          type: entities
          title: Smart Plug 1
        filter:
          include:
            - entity_id: "*.smart_plug_1*"

      - type: "custom:monster-card"
        id: smart-plug-2
        card:
          type: entities
          title: Smart Plug 2
        filter:
          include:
            - entity_id: "*.smart_plug_2*"

      - type: "custom:monster-card"
        id: zwave_batteries
        card:
          type: entities
          title: Batteries
        filter:
          include:
            - entity_id: "sensor.*_battery"

      - title: Bathroom MultiSensor
        id: bathroom_multisensor
        type: entities
        entities:
          - sensor.bathroom_alarm_level
          - sensor.bathroom_alarm_type
          - sensor.bathroom_burglar
          - sensor.bathroom_sourcenodeid
          - sensor.bathroom_temperature
          - sensor.bathroom_ultraviolet

      - title: Front Door Lock
        id: front_door_lock
        type: entities
        entities:
          - sensor.front_door_lock_access_control
          - sensor.front_door_lock_alarm_level
          - sensor.front_door_lock_alarm_type
          - sensor.front_door_lock_burglar
          - sensor.front_door_lock_power_management
          - sensor.front_door_lock_sourcenodeid
          - sensor.front_door_lock_system
